name: punch_card_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15  # 用于本地数据存储
  table_calendar: ^3.1.8  # 用于日历组件
  syncfusion_flutter_charts: ^28.2.5+1  # 用于 Echarts 柱状图
  intl: ^0.20.0  # 添加这一行
  path_provider: ^2.1.1  # 用于文件路径获取
  permission_handler: ^11.0.1  # 用于权限管理
  file_picker: ^8.1.4  # 使用更新的兼容版本，支持 v2 embedding

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true